# Generated by Django 5.2 on 2025-05-01 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Basket',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='BasketItem',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='cart',
            new_name='basket',
        ),
    ]
