# Generated by Django 5.2 on 2025-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_product_description_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
