# Generated by Django 5.2rc1 on 2025-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
