# Generated by Django 5.2rc1 on 2025-04-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core4', '0006_service_remove_contact_content_remove_contact_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='Home',
        ),
    ]
