# Generated by Django 5.2rc1 on 2025-04-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core4', '0007_rename_aboutus_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='AboutUs',
        ),
    ]
