# Generated by Django 5.2rc1 on 2025-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core4', '0009_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
